/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 10 03:26:11 GMT 2023
 */

package evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import views.Alert;
import views.AlertStateContext;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class AlertStateContext_ESTest extends AlertStateContext_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AlertStateContext alertStateContext0 = new AlertStateContext();
      String string0 = alertStateContext0.alert();
      assertEquals("Available", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AlertStateContext alertStateContext0 = new AlertStateContext();
      alertStateContext0.setState((Alert) null);
      // Undeclared exception!
      try { 
        alertStateContext0.alert();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("views.AlertStateContext", e);
      }
  }
}
