/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 10 03:27:19 GMT 2023
 */

package evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import views.AlertStateContext;
import views.Available;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class Available_ESTest extends Available_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Available available0 = new Available();
      AlertStateContext alertStateContext0 = new AlertStateContext();
      String string0 = available0.alert(alertStateContext0);
      assertEquals("Available", string0);
  }
}
