/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 10 03:22:42 GMT 2023
 */

package evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import password.Generator;
import password.NumberPasswordBuilder;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class Generator_ESTest extends Generator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Generator generator0 = new Generator();
      NumberPasswordBuilder numberPasswordBuilder0 = new NumberPasswordBuilder();
      generator0.setPasswordBuilder(numberPasswordBuilder0);
      generator0.generatePassword();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Generator generator0 = new Generator();
      // Undeclared exception!
      try { 
        generator0.generatePassword();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("password.Generator", e);
      }
  }
}
