/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 10 03:12:45 GMT 2023
 */

package evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import controllers.LotController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class LotController_ESTest extends LotController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      LotController.enableLot("q|Y");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      LotController.removeLot("q|Y");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      LotController lotController0 = new LotController();
      //  // Unstable assertion: assertEquals("", lotController0.getLotList());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      LotController.clear();
      LotController.getLotList();
      LotController.clear();
      FileSystemHandling fileSystemHandling0 = new FileSystemHandling();
      LotController.removeLot(",");
      LotController.removeLot("(H6d)pIzEq$$KEA");
      LotController.clear();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      LotController.resetLots();
  }
}
