/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 10 03:16:12 GMT 2023
 */

package evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.FileNotFoundException;
import model.MaintainManager;
import model.MaintainUser;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class Maintain_ESTest extends Maintain_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MaintainManager maintainManager0 = MaintainManager.getInstance();
      maintainManager0.update();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MaintainManager maintainManager0 = MaintainManager.getInstance();
      maintainManager0.clear();
      maintainManager0.load();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MaintainUser maintainUser0 = MaintainUser.getInstance();
      try { 
        maintainUser0.load();
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // File C:\\Users\\natal\\eecs3311project\\user.csv does not exist.
         //
         verifyException("com.csvreader.CsvReader", e);
      }
  }
}
