/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 10 03:17:19 GMT 2023
 */

package evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.FileNotFoundException;
import java.io.IOException;
import model.MaintainLot;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = false, useJEE = true) 
public class MaintainLot_ESTest extends MaintainLot_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MaintainLot maintainLot0 = MaintainLot.getInstance();
      maintainLot0.update();
      FileSystemHandling.shouldAllThrowIOExceptions();
      try { 
        maintainLot0.load();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Simulated IOException
         //
         verifyException("org.evosuite.runtime.vfs.VirtualFileSystem", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MaintainLot maintainLot0 = MaintainLot.getInstance();
      try { 
        maintainLot0.load();
        fail("Expecting exception: FileNotFoundException");
      
      } catch(FileNotFoundException e) {
         //
         // File C:\\Users\\natal\\eecs3311project\\lot.csv does not exist.
         //
         verifyException("com.csvreader.CsvReader", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MaintainLot maintainLot0 = MaintainLot.getInstance();
      maintainLot0.clear();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MaintainLot maintainLot0 = MaintainLot.getInstance();
      maintainLot0.resetLotOptions();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      MaintainLot maintainLot0 = MaintainLot.getInstance();
      maintainLot0.update();
      maintainLot0.load();
  }
}
