/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 10 03:13:53 GMT 2023
 */

package evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import controllers.ManagerController;
import java.util.ArrayList;
import objects.Manager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ManagerController_ESTest extends ManagerController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // Undeclared exception!
      try { 
        ManagerController.logInManager((String) null, (String) null);
       //  fail("Expecting exception: NullPointerException");
       // Unstable assertion
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String string0 = ManagerController.logInManager("SuperManager", ";e>7");
      //  // Unstable assertion: assertEquals("Password incorrect.", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String string0 = ManagerController.logInManager("SuperManager", "Aa!1");
      //  // Unstable assertion: assertEquals("Password incorrect.", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ManagerController.resetManager();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ManagerController.logOutManager();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ArrayList<Manager> arrayList0 = ManagerController.getManagers();
      assertTrue(arrayList0.isEmpty());
  }
}
