/*
 * This file was automatically generated by EvoSuite
 * Mon Apr 10 03:25:04 GMT 2023
 */

package evosuite;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import password.Password;
import password.StrongPasswordBuilder;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StrongPasswordBuilder_ESTest extends StrongPasswordBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      StrongPasswordBuilder strongPasswordBuilder0 = new StrongPasswordBuilder();
      Password password0 = strongPasswordBuilder0.getPassword();
      assertEquals("", password0.getPassword1());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      StrongPasswordBuilder strongPasswordBuilder0 = new StrongPasswordBuilder();
      strongPasswordBuilder0.setIncludeNumbers();
      Password password0 = strongPasswordBuilder0.getPassword();
      assertTrue(password0.getIncludeNumbers());
      assertEquals("", password0.getPassword1());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StrongPasswordBuilder strongPasswordBuilder0 = new StrongPasswordBuilder();
      strongPasswordBuilder0.setIncludeSymbols();
      Password password0 = strongPasswordBuilder0.getPassword();
      assertTrue(password0.getSymbols());
      assertEquals("", password0.getPassword1());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      StrongPasswordBuilder strongPasswordBuilder0 = new StrongPasswordBuilder();
      strongPasswordBuilder0.setLowerCase();
      Password password0 = strongPasswordBuilder0.getPassword();
      assertEquals("", password0.getPassword1());
      assertTrue(password0.getincludeLowerCase());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      StrongPasswordBuilder strongPasswordBuilder0 = new StrongPasswordBuilder();
      strongPasswordBuilder0.setUpperCase();
      Password password0 = strongPasswordBuilder0.getPassword();
      assertTrue(password0.getincludeUpperCase());
      assertEquals("", password0.getPassword1());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      StrongPasswordBuilder strongPasswordBuilder0 = new StrongPasswordBuilder();
      strongPasswordBuilder0.setLength();
      Password password0 = strongPasswordBuilder0.getPassword();
      assertEquals("aaaaaaaa", password0.getPassword1());
  }
}
